// Extracts the original game's data from DIGGER.COM (Windmill Software, 1983) into
// src/assets/original.ts. Run with: node tools/extract/extract.ts
//
// Where each item lives in the file is recorded in manifest.json (offsets were found
// by matching against Digger Remastered's tables); every byte written out is read from
// the original program.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type SpriteEntry = {
  ch: number;
  sprite: string;
  mask: string;
  w: number;
  h: number;
  spriteOff: number | null;
  maskOff: number | null;
};
type Manifest = {
  source: { file: string; size: number; sha256: string; origin: string };
  sprites: SpriteEntry[];
  font: { w: number; h: number; glyphs: { glyph: string; off: number }[] };
  levels: { off: number; count: number; rows: number; cols: number };
  tunes: Record<string, { off: number; words: number }>;
  codeImmediates: Record<string, { offsets: number[] }>;
  texts: { off: number; text: string }[];
};

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const manifest: Manifest = JSON.parse(readFileSync(join(root, "tools/extract/manifest.json"), "utf8"));
const bin = readFileSync(join(root, manifest.source.file));

const sha = createHash("sha256").update(bin).digest("hex");
if (sha !== manifest.source.sha256) throw new Error(`unexpected DIGGER.COM (sha256 ${sha})`);

const hex = (off: number, len: number) => bin.subarray(off, off + len).toString("hex");
const word = (off: number) => bin.readUInt16LE(off);

// sprites: w is in bytes (4 pixels each); fire/explosion frames are read with the
// same 16-byte length the game draws them with, overlapping the following block
const sprites: Record<number, { name: string; w: number; h: number; data: string; mask: string | null }> = {};
for (const e of manifest.sprites) {
  if (e.spriteOff === null) continue;
  const len = e.w * e.h;
  sprites[e.ch] = {
    name: e.sprite.replace(/^cga/, ""),
    w: e.w,
    h: e.h,
    data: hex(e.spriteOff, len),
    mask: e.maskOff === null ? null : hex(e.maskOff, len),
  };
}

const font: Record<string, string> = {};
for (const g of manifest.font.glyphs)
  if (g.off >= 0) font[g.glyph] = hex(g.off, manifest.font.w * manifest.font.h);

const L = manifest.levels;
const levels: string[][] = [];
for (let l = 0; l < L.count; l++) {
  const rows: string[] = [];
  for (let r = 0; r < L.rows; r++) {
    const o = L.off + (l * L.rows + r) * L.cols;
    rows.push(bin.subarray(o, o + L.cols).toString("latin1"));
  }
  levels.push(rows);
}

const tunes: Record<string, number[]> = {};
for (const [name, t] of Object.entries(manifest.tunes))
  tunes[name] = Array.from({ length: t.words }, (_, i) => word(t.off + i * 2));

const immediates: Record<string, number[]> = {};
for (const [name, t] of Object.entries(manifest.codeImmediates)) immediates[name] = t.offsets.map(word);

// title screen: a length word followed by the RLE-compressed CGA video memory image
const titleLenOff = (manifest as unknown as { title: { lengthWordOff: number } }).title.lengthWordOff;
const titleRle = hex(titleLenOff + 2, word(titleLenOff));

const texts = manifest.texts.map((t) => {
  const got = bin.subarray(t.off, t.off + t.text.length).toString("latin1");
  if (got !== t.text) throw new Error(`text mismatch at ${t.off}: ${JSON.stringify(got)}`);
  return t.text;
});

const out = `// GENERATED by tools/extract/extract.ts from the original DIGGER.COM
// (Windmill Software, 1983; ${manifest.source.origin}). Do not edit.
// sha256 ${sha}

export const ORIGINAL_SHA256 = ${JSON.stringify(sha)};

/** Sprites by the game's sprite number: w in bytes (4 px each), h in rows, CGA bytes as hex. */
export const sprites: Record<number, { name: string; w: number; h: number; data: string; mask: string | null }> = ${JSON.stringify(sprites, null, 1)};

/** Font glyphs, 3 bytes (12 px) x 12 rows each, CGA bytes as hex. */
export const font: Record<string, string> = ${JSON.stringify(font, null, 1)};

/** The 8 level maps, 10 rows of 15 cells (S, B, H, V, C, space) as stored in the game. */
export const levels: string[][] = ${JSON.stringify(levels, null, 1)};

/** Music: PIT divisor / duration word pairs as stored in the game. */
export const tunes: Record<string, number[]> = ${JSON.stringify(tunes)};

/** Sound values the game keeps as immediate operands in its code. */
export const soundImmediates: Record<string, number[]> = ${JSON.stringify(immediates)};

/** Title screen, RLE-compressed CGA video memory (FE count value; count 0 = 256). */
export const titleRle = ${JSON.stringify(titleRle)};

/** Texts the game prints. */
export const texts: string[] = ${JSON.stringify(texts, null, 1)};
`;
writeFileSync(join(root, "src/assets/original.ts"), out);
console.log(`wrote src/assets/original.ts: ${Object.keys(sprites).length} sprites, ${Object.keys(font).length} glyphs, ${levels.length} levels, tunes ${Object.keys(tunes).join("/")}`);
